version: 1
formatters:
  simple:
    format: '%(asctime)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: INFO
    filename: tic_tac_toe.log
    maxBytes: 1024
    backupCount: 150
loggers:
  sampleLogger:
    level: INFO
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [file]